version: 2.1

# TODO: Modify to work with the CircleCI Node.js orb
# orbs:
#   node: circleci/node@4.3.0

jobs:
  run_migrations:
    docker:
      - image: circleci/node:14.16
    parameters:
      fauna_admin_key:
        description: Fauna admin/server key for a given environment
        type: string
    environment:
      FAUNA_ADMIN_KEY: << parameters.fauna_admin_key >>
    steps:
      - checkout
      - run: npm ci
      - run: npx fauna-schema-migrate generate
      - run: npx fauna-schema-migrate apply
      - run: npx fauna-schema-migrate state

workflows:
  workflow:
    jobs:
      - run_migrations:
          name: build-staging
          filters:
            branches:
              only: staging
          fauna_admin_key: $STAGING_FAUNA_ADMIN_KEY

      - run_migrations:
          name: build-production
          filters:
            branches:
              only: main
          fauna_admin_key: $PRODUCTION_FAUNA_ADMIN_KEY
