# Copyright Fauna, Inc.
# SPDX-License-Identifier: MIT-0

version: 2.1

jobs:
  run_migrations:
    docker:
      - image: circleci/node:14.16
    steps:
      - checkout
      - run: npm ci
      - run: npx fauna-schema-migrate state
      - run: npx fauna-schema-migrate generate
      - run: npx fauna-schema-migrate apply all
      - run: npx fauna-schema-migrate state

workflows:
  workflow:
    jobs:

      - run_migrations:
          name: build-production
          context:
            - orb-publishing
          filters:
            branches:
              only: main
